// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmudcfonpwabrvpfznyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtdWRjZm9ucHdhYnJ2cGZ6bnl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNzU5OTYsImV4cCI6MjA2ODY1MTk5Nn0.l9G7tp-efLpAi0m_WL5GXzY9k1r_WQUrbQWP1_rWT5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});